[package]
name = "gsm-serde-derive"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://gsm.boop.ninja/gsm_serde_derive/index.html"
description = "Derive macro companion to gsm-serde: implements IniHeader via #[INIHeader(name = \"...\")]."


[lib]
proc-macro = true  # Enable procedural macro support


[dependencies]
syn = { version = "2.0", features = ["derive", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"

[lints]
workspace = true
