name: Docker Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  Release:
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: mbround18/gsm-reference
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
