name: PR Pipelines

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  rust-build-and-test:
    uses: mbround18/gh-reusable/.github/workflows/rust-build-n-test.yaml@main
    with:
      toolchain: "1.95"
      components: clippy,rustfmt

  audit:
    uses: mbround18/gh-reusable/.github/workflows/audit.yaml@main

  dependency-review:
    uses: mbround18/gh-reusable/.github/workflows/dependency-review.yaml@main
