name: Tag Crates
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      GITHUB_EVENT_PATH: ${{ github.event_path }}
      GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tagger
        uses: ./.github/actions/tagger
